name: Changelog Generator

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - development
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Changelog
        uses: metcalfc/changelog-generator@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
