name: Changelog Generator

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - development
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    name: Changelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bala-raj/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
